### ISSUE TITLE
incomplete register support for 16-bit and 32-bit modes?

### ISSUE THREAD

**Issue by iximeow** [Vector35/arch-x86#7]
admission: this is purely from reading the source - if I've misunderstood `GetRegisterInfo` or how lifting fits together. i don't have a binja license to go find out, so if this entirely nonsense .. my bad, sorry! 

32-bit and 16-bit x86 vex-encoded and evex-encoded instructions, and consequently may have operand registers `ymm[0, 7]` and even `zmm[0, 7]`. it looks like the 32-bit lifting [here](https://github.com/Vector35/arch-x86/blob/master/arch_x86.cpp#L2989-L2998) would report such registers as invalid, and likewise 16-bit lifting is entirely unaware of [simd registers](https://github.com/Vector35/arch-x86/blob/master/arch_x86.cpp#L3091-L3092)

given that instructions like `VMOVUPS` have a lifting that looks [architecture independent](https://github.com/Vector35/arch-x86/blob/master/il.cpp#L2080-L2101) it seems like putting a `c5fc100f` (in protected mode: `vmovups ymm1, [edi]`) ought to be a quick and easy check?

"come on, what real programs have such instructions??" a fair question! off the top of my head, csaw 2017's `realism` challenge (copy of the binary is [here](https://github.com/TechSecCTF/writeups/tree/master/CSAWQuals2017/realism)) involved real-mode use of simd (including aesni!) instructions, which most tools did not behave well on :grin:

**Comment by KyleMiles** [comment]
Looks good to me? 
![image](https://user-images.githubusercontent.com/7171118/97352505-210c0280-1869-11eb-9402-588b8499da2d.png)

Source for challenge is [here](https://github.com/osirislab/CSAW-CTF-2017-Quals/blob/master/rev/realism/main.s).

**Comment by psifertex** [comment]
Also, for what it's worth, you can probably open up sample binaries on cloud (https://cloud.binary.ninja/) to test the current disassembly. One downside is that you can't create arbitrary functions with arbitrary hex blobs right now, hopefully we can get to adding that feature. 

Also, signups are currently disabled due to a spam attack on the signup page, but happy to manually create accounts if you email cloud at vector35 dot com.

**Comment by KyleMiles** [comment]
That function actually fails to lift because of the int 0x10 at the top... While there may be other lifting issues, the solution is just to create a 32 or 64 bit function at that address.  I don't believe any 16 bit or early 32 bit processors had SIMD instructions (correct me if I'm wong).  Though (and again, correct me if I'm wrong), you can access any registers your processor has in real mode.  So a 32-bit processor with SIMD instructions/registers in the bootloader should be lifted as a 32-bit function.

These architectures represent the hardware capabilities, not the processor modes.

**Comment by iximeow** [comment]
fwiw i patched a 32-bit binary to use a ymm register and can get an `invalid` out of cloud.binary.ninja:

this C:
```
int main(int argc, char** argv) {
  printf("hello, how are you? %d\n", argc + 10);
}
```

compiled (`gcc -m32 file.c`) into

![pre-patching](https://user-images.githubusercontent.com/4615790/97361584-fa47cf00-185c-11eb-8b23-0eab4f1e4ad4.png)

and i patched the `mov eax, 0` into a `vmovups` and `nop`:

![post-patching](https://user-images.githubusercontent.com/4615790/97362122-c0c39380-185d-11eb-9299-083bb83fa3ce.png)

to get a `ymm`-using instruction in a 32-bit binary. messy, but it ?works?:

disassembly is fine:
![disassembly](https://user-images.githubusercontent.com/4615790/97364740-b6a39400-1861-11eb-8a57-e838e76398d7.png)

but `MLIL` has an `invalid`:
![mlil](https://user-images.githubusercontent.com/4615790/97364810-d2a73580-1861-11eb-95f2-c95cd9687277.png)

what has me wondering if this is actually the bug is, `LLIL` shows a write to `ymm1`?
![llil](https://user-images.githubusercontent.com/4615790/97364848-e6eb3280-1861-11eb-87d3-1e76fd8db3f3.png)
